# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ade205e93fc49868a11c47e8128ecaa3f9a7b3bd24514d5c5224fa983cc80a6402b65a43d7a4e37a9e0d95cd96c5e6dab3ce856f40ca18923f10fb5da0139d46

test:
  secret_key_base: 962eea4376ead19d8404761100407e31a57c8a3e6bd8b1d64da30721214573ad5e44af0c0342a205c2494d0dac68799f03dfc3c06887362d3d55265c5c88ea2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
